### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by tranduyduong** [2ksoft/todo-app#1]
Về tổng thế code rất clean từ việc viết code, tách component. Anh thấy có 1 đoạn dưới đây  nhìn hơi rối 

  todos =
    filter == undefined
      ? todos
      : filter === "COMPLETED"
      ? todos.filter((todo) => todo.isCompleted)
      : todos.filter((todo) => !todo.isCompleted);
Trong thực tế anh cũng gặp kiểu viết như này vài lần, cách việt này khá là tiện, nhưng cũng rất dễ nhầm, và cũng khó hình dung code hơn nếu như mình cho thêm mấy cái đóng, mở ngoặc vào thì code sẽ dễ hình dùng hơi, với những biểu thức mix nhau như thế này thì mình cần đánh đổi giữa việc viết code nhanh gọn bằng việc code dễ hiểu hơn cho đồng nghiệp, và dễ trace lỗi sau này. Anh nghĩ chỗ này mình nên dùng if, else để viết sẽ clear  hơn ^^

**Comment by tranduyduong** [comment]
tương tự, anh nghĩ mình cũng không nên dùng return state.filter((todo) => todo.id != action.id); cho việc delete 1 element,  cách này không sai, nhưng anh nghĩ hàm map() & filter(), mục đích chính của nó không phải để dùng cho việc update và delete như này, anh đọc đâu đấy thì thường các bạn không recommend dùng cách này.

từ trước đến nay anh vẫn trung thành với hướng dẫn của bạn này: 
[https://github.com/wesbos/Learn-Redux/blob/master/client/reducers/posts.js] & [https://github.com/wesbos/Learn-Redux/blob/master/client/reducers/comments.js]

**Comment by hashcott** [comment]
oke anh em sẽ tham khảo ạ <3
