### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by tranduyduong** [2ksoft/todo-app#2]
Liên quan đến việc update data trong reducer, 
return state.map((todo) =>
        todo.id == action.id
          ? { ...todo, isCompleted: !todo.isCompleted }
          : todo
      );
Anh vẫn nghĩ mình không nền dùng map() function để update, về lý thuyết thì việc nãy sẽ phải loop qua toàn bộ array, array bé thì ok, nhưng array lớn anh nghĩ sẽ có  một chút xíu về performance,  vì thực tế mình có thể pass thẳng item index vào sử dụng es6 spread operator để xử lý.

**Comment by hashcott** [comment]
oke anh ạ <3
